spring.application.name=placement-clash-resolver

# ==============================
# MySQL
# ==============================
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# ==============================
# JPA
# ==============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# ==============================
# AI / Gemini
# ==============================
spring.ai.google.genai.api-key=${GEMINI_API_KEY}
spring.ai.google.genai.chat.options.model=gemini-2.5-flash

# ==============================
# Server
# ==============================
server.port=${PORT:8080}